### PR TITLE
Add tslint engine

### PR DESCRIPTION
**Pull request by 9r0x**
This PR will introduce new engine "tslint" and it's mostly for TypeScript language.

Closes https://github.com/repometric/linterhub-docker/issues/2

### CODE REVIEW

**Comment by yukiisbored** [comment]
LGTM.
Ping @xferra

**Review by xferra — CHANGES_REQUESTED** [review]
@Grox-Ni Thank you for your first contribution, great job! Dockerfile looks good for me, but could you please add a simple test? You can use #5 as an example.

**Comment by 9r0x** [comment]
@xferra I've added the tests with my own example.ts because most typescript repos are already linted and those repos could change, which might break the test.

**Comment by andrewda** [comment]
@Grox-Ni I believe gitmodules are snapshotted to a single commit so they won't change over time. This looks good, though!

**Comment by 9r0x** [comment]
Yes, you are right about git submodule. 

I am thinking if we build a unit test (like my sample.ts) for every engine, it will be clearer for other maintainers to go through the code and also it is lighter.

**Comment by yukiisbored** [comment]
@Grox-Ni Since we don't have a unit test system atm, something like test if it'll fail or not is enough for now ;)

**Comment by 9r0x** [comment]
@xferra OK, since most main TypeScript repositories are using tslint already. I am thinking still use my test. What do you think😉

**Comment by 9r0x** [comment]
@yukiisbored Imao, https://github.com/flycheck/flycheck has a good design of unit test if we want to implement one in the future

**Comment by xferra** [comment]
I think it's enough to have a very simple test which will validate that linter inside container could be executed and linting results from host and container are equal; it doesn't matter whether it will be an external project or some files created manually. Let's treat it as 'integration test for sanity check' 🙃. Regarding unit tests - we will not be able to test everything and `tslint` repo is the better place for that.
As for the rest - PR looks good for me, good job!

**Review by xferra — APPROVED** [review]

**Pull request merged**
